# Generated by Django 5.0.7 on 2024-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_solution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
