# Generated by Django 5.0.7 on 2024-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_solution_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
