# Generated by Django 5.0.7 on 2024-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
