# Generated by Django 5.0.7 on 2024-12-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0007_alter_solution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
