# Generated by Django 5.0.7 on 2024-12-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_alter_solution_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
